services:
  - type: web
    name: music-web-be
    env: docker
    plan: free
    branch: main
    repo: https://github.com/dung2502/Music-Fe
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: SPRING_APPLICATION_NAME
        value: music-web-be
      - key: SERVER_PORT
        value: 8080
      - key: DB_URL
        value: jdbc:mysql://localhost:3306/music-web?createDatabaseIfNotExist=true
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: 123456
      - key: FIREBASE_CREDENTIAL_PATH
        value: src/main/resources/firebase-key/logingo-4d97c-firebase-adminsdk-666z6-63f42e4eb8.json
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:3000,http://localhost:3001
